### ISSUE TITLE
Can votes be casted from API ? 

### ISSUE THREAD

**Issue by tamalsen** [getamis/go-ethereum#153]
Geth version: geth version: 1.7.2

OS & Version: Windows/Linux/OSX: Linux

I have just started tinkering with blockchain and found this really awesome library. I have a very basic confusion about using various consensus algorithms. Can the votes be casted through API and delay creating a block until a threshold (lets say n/2 + 1) is reached. If so, how can I do that while using Istanbul BFT on Quorum?

**Comment by markya0616** [comment]
Yes, we provided vote RPC API. Please refer https://github.com/getamis/go-ethereum/wiki/RPC-API .

**Comment by tamalsen** [comment]
Sorry I might be completely dumb, but I can't find any api called 'vote'. Can you please elaborate how to do it ?

**Comment by markya0616** [comment]
No, you can't delay creating a block. If you want to vote someone in, you can use https://github.com/getamis/go-ethereum/wiki/RPC-API#istanbulpropose.

**Comment by tamalsen** [comment]
Thanks a lot @markya0616
